type: production
backend:
  logging:
    logdir: logs
server:
  dev:
    http_port: 3241
    https_port: 3240
  production:
    http_port: 3241
    https_port: 3240
  force_https: true
  https:
    key: /etc/letsencrypt/live/misc.twoseven.xyz/privkey.pem
    cert: /etc/letsencrypt/archive/misc.twoseven.xyz/fullchain.pem
  proxy_path: &proxypath https://misc.twoseven.xyz:3240/
